logic_table: logic_table.o logic_table.hpp parse_data.o
	clang++ -o logic_table logic_table.o parse_data.o

logic_table.o:
	clang++ -c logic_table.cpp

parse_data.o:
	clang++ -c parse_data.cpp

Check out
https://stackoverflow.com/questions/2394609/makefile-header-dependencies
